### PR TITLE
feat: add a dummy news page with correct UI

### PR DESCRIPTION
**Pull request by ClementJosso**
This should be a working news page, it just needs the viewmodel to get the actual data of the user.

To test it, you can edit line 40 of main.dart to have : "body = const NewsView();" (and import news_view.dart)

### CODE REVIEW

**Review by Thechi2000 — COMMENTED** [review]
Just a nit pick, otherwise good work !

**Review by Pacsort17 — CHANGES_REQUESTED** [review]
Should be changed :
Tested on edge and android : the overlay when passing the mouse / finger over the news is contained in the text instead of surrounding it (the text should be in the pink rectangle, not the other way around).

Works :
The view is scrollable and detects when it's clicked, outputting a source.

**Review by Pacsort17 — APPROVED** [review]
Overlay for sources is not there anymore (except pour AppBar). Clicking on the text still gives the source (only text 4 outputs "source2"), and clicking somewhere else (like titles) doesn't output anything.

**Review by Thechi2000 — APPROVED** [review]
Only tested on Linux, not Android. Looks great !

**Pull request merged**
