### PR TITLE
chore: add code format check to client hooks

### LINKED ISSUE #24: dev: add code lint to client hooks

### PR DESCRIPTION
**Pull request by Thechi2000**
Add a pre-commit hook to check the formatting of the `.dart` files. The installation command in the README has changed, since the hook needs to be triggered on pre-commit (not commit-msg).

I added a python script to handle the check, for portability. I would still like at least a review on each platform (Linux, Windows, MacOS).

Closes #24

### CODE REVIEW

**Review by pmdlt — APPROVED** [review]
Work well on Linux (Codespaces Env.)
I had to `sudo ln -s /home/codespace/.python/current/bin/python /usr/bin/python`

**Review by Pacsort17 — CHANGES_REQUESTED** [review]
Got "Executable `/usr/bin/python` not found" when running the run command (last one).

**Review by Pacsort17 — APPROVED** [review]
Works on Windows, thanks :)

**Review by quartztz — APPROVED** [review]
I pass all of my test !!

Jokes aside, looks great to me. Thanks for the work !

**Review by Pacsort17 — APPROVED** [review]
Works well on Windows.

However, when a file is misformated, every command and path is red until a pre-commit run pass.

**Pull request merged**
