### PR TITLE
38 feat authentication UI

### PR DESCRIPTION
**Pull request by quartztz**
Clean up and get UI closer to Figma. Behavior for guest sign in can be tested in chrome, behavior for google sign in works best on devices. 

Please review!!

### CODE REVIEW

**Comment by quartztz** [comment]
As always when introducing a new platform, sonarcloud complains... Best practice would have me create a new PR to fix its config, but having discussed irl with the team, it's going to be faster and more relevant to just change the config on this branch and approve both changes as well. So that's that!

**Review by Thechi2000 — APPROVED** [review]
Great job ! Tested on Linux and Android.

Just a small question: why did you need to change the macos specific files ?

**Comment by Thechi2000** [comment]
@quartztz It's perfectly fine, I was just wondering if there was a particular reason (e.g. the auth did not work on mac).

**Comment by quartztz** [comment]
Oh no, I think it's just flutter behavior. Still untested on `macos`, but works on android!

**Review by loggerz — CHANGES_REQUESTED** [review]
We should not add another platform as some features need specific implementation. Main platform is android and web + linux are used for testing purposes

**Comment by quartztz** [comment]
Oh! I see. I'll remove them from the repo.

**Review by Thechi2000 — APPROVED** [review]

**Review by loggerz — APPROVED** [review]

**Pull request merged**
