### PR TITLE
chore: fix format check hook

### PR DESCRIPTION
**Pull request by Thechi2000**
Fix the client hook to correctly detect non-formatted code. Also fix color persistence in the shell after a failure.

### CODE REVIEW

**Comment by pmdlt** [comment]
@Thechi2000 Why not directly `dart format lib` ?
And prompt an error if not fixed (witch is a possibility)

**Comment by Thechi2000** [comment]
> @Thechi2000 Why not directly `dart format lib` ? And prompt an error if not fixed (witch is a possibility)

I personally don't like having hooks modifying the commit, even if it says it. I prefer knowing exactly what is committed, without having to check afterwards. But I understand, and we can do it if the majority wants it.

**Comment by Thechi2000** [comment]
> @Thechi2000 Why not directly `dart format lib` ? And prompt an error if not fixed (witch is a possibility)

I personally don't like having hooks modifying the commit, even if it says it. I prefer knowing exactly what is committed, without having to check afterwards. But I understand, and we can do it if the majority wants it.

**Review by pmdlt — APPROVED** [review]
Okay :) so go on, lgtm

**Review by ClementJosso — APPROVED** [review]
Tested on Windows, commits with incorrect code format are indeed blocked and the red color of the warning doesn't stay after :)

**Pull request merged**
