### PR TITLE
147 View for context from OCR

### PR DESCRIPTION
**Pull request by ClementJosso**
This small PR adds the view for the new epic, i.e. it displays the text generated by an LLM after the users takes a picture of some news text in order to get context about it. 

**Testing** is easy, exactly the same as for[ PR 145](https://github.com/ActualIA/app/pull/145), click on the camera icon, take a picture of some news text you see, and you should soon see a new view with context about your picture.
If you leave this view, you won't be able to come back since clicking on the camera icon again will make you take another picture.

**IMPORTANT:** Do not merge this until PRs [148](https://github.com/ActualIA/app/pull/148) and [145](https://github.com/ActualIA/app/pull/145) have been merged, since this PR relies on them. (Right now it says +500 lines but it's actually closer to 50, this is because the other ones haven't been merged yet)

### CODE REVIEW

**Review by LeanderCretegny — COMMENTED** [review]
_deleted_

**Review by LeanderCretegny — APPROVED** [review]
Code is good, and work fine on my emulator.

**Comment by pmdlt** [comment]
(fix `the merge-base changed after approval`)

**Review by pmdlt — APPROVED** [review]
Looks good for merging :)

**Review by Pacsort17 — APPROVED** [review]
It seems to have some problems for complexe articles, like Ukrainian war. I tested on a easier example (Georgia's political alignement) and it worked well !

**Pull request merged**
